// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcTokoOnline.Data;

namespace MvcTokoOnline.Migrations
{
    [DbContext(typeof(MvcTokoOnlineDbContext))]
    [Migration("20211022082042_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MvcTokoOnline.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("MvcTokoOnline.Models.Kategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("MvcTokoOnline.Models.Produk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("KategoriID")
                        .HasColumnType("longtext");

                    b.Property<string>("Nama")
                        .HasColumnType("longtext");

                    b.Property<string>("Ukuran")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("MvcTokoOnline.Models.SistemPembayaran", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MetodePembayaran")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("sistemPembayarans");
                });

            modelBuilder.Entity("MvcTokoOnline.Models.Transaksi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CustomerID")
                        .HasColumnType("longtext");

                    b.Property<string>("SistemPembayaranID")
                        .HasColumnType("longtext");

                    b.Property<string>("TanggalPembayaran")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("MvcTokoOnline.Models.TransaksiDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Jumlah")
                        .HasColumnType("longtext");

                    b.Property<string>("ProdukID")
                        .HasColumnType("longtext");

                    b.Property<string>("TransaksiID")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("transaksiDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
